
line-length = 108

target-version = "py310"

[lint]

select = ["E", "W", "F"]

[format]
# 5. Use single quotes for non-triple-quoted strings.
quote-style = "double"
indent-style = "space"

skip-magic-trailing-comma = false
line-ending = "auto"